package com.example.ui.localization

import androidx.compose.runtime.Composable
import androidx.compose.runtime.compositionLocalOf

data class AppStrings(
    val appName: String,
    val home: String,
    val medicines: String,
    val calendar: String,
    val family: String,
    val more: String,
    val todayOverview: String,
    val todaysMedicines: String,
    val upcomingDoses: String,
    val completedDoses: String,
    val missedDoses: String,
    val upcomingAppointments: String,
    val expiringSoon: String,
    val quickActions: String,
    val addMedicine: String,
    val addFamilyMember: String,
    val addDoctor: String,
    val addAppointment: String,
    val uploadPrescription: String,
    val noMedicinesTitle: String,
    val noFamilyMembersTitle: String,
    val noAppointmentsTitle: String,
    val noPrescriptionsTitle: String,
    val noDoctorsTitle: String,
    val noCaregiversTitle: String,
    val noHistoryTitle: String,
    val taken: String,
    val skip: String,
    val snooze: String,
    val snooze10m: String,
    val snooze30m: String,
    val snooze1h: String,
    val lowStock: String,
    val expired: String,
    val expiringInDays: String,
    val doctors: String,
    val prescriptions: String,
    val caregivers: String,
    val inventory: String,
    val history: String,
    val reports: String,
    val settings: String,
    val search: String,
    val notifications: String,
    val aboutAuthor: String,
    val activeMedicines: String,
    val profile: String,
    val edit: String,
    val delete: String,
    val save: String,
    val cancel: String,
    val confirmDelete: String,
    val confirmDeleteMsg: String,
    val medicineName: String,
    val genericName: String,
    val medicineType: String,
    val strength: String,
    val unit: String,
    val dosage: String,
    val quantity: String,
    val remainingQuantity: String,
    val minThreshold: String,
    val startDate: String,
    val endDate: String,
    val frequency: String,
    val doseTimes: String,
    val addDoseTime: String,
    val beforeAfterFood: String,
    val prescribedByDoctor: String,
    val selectFamilyMember: String,
    val medicineNotes: String,
    val expiryDate: String,
    val fullName: String,
    val nickname: String,
    val dob: String,
    val gender: String,
    val bloodGroup: String,
    val phone: String,
    val relationship: String,
    val doctorName: String,
    val specialty: String,
    val hospitalClinic: String,
    val email: String,
    val address: String,
    val call: String,
    val message: String,
    val openMap: String,
    val appointmentDate: String,
    val appointmentTime: String,
    val reason: String,
    val reminderTime: String,
    val status: String,
    val markCompleted: String,
    val reschedule: String,
    val prescriptionTitle: String,
    val notes: String,
    val caregiverName: String,
    val notifyMissed: String,
    val notifyReminder: String,
    val notifyAppointment: String,
    val notifyExpiry: String,
    val caregiverAlertInfo: String,
    val exportData: String,
    val backupData: String,
    val restoreData: String,
    val clearData: String,
    val appPin: String,
    val privateNotification: String,
    val privateNotificationDesc: String,
    val language: String,
    val appearance: String,
    val lightMode: String,
    val darkMode: String,
    val systemDefault: String,
    val getStarted: String,
    val notificationPermissionDesc: String,
    val allowNotifications: String,
    val complianceRate: String,
    val totalDoses: String,
    val searchPlaceholder: String,
    val noResultsFound: String,
    val all: String
)

val EnglishStrings = AppStrings(
    appName = "Medicine Sathi",
    home = "Home",
    medicines = "Medicines",
    calendar = "Calendar",
    family = "Family",
    more = "More",
    todayOverview = "Today's Overview",
    todaysMedicines = "Today's Medicines",
    upcomingDoses = "Upcoming Doses",
    completedDoses = "Completed Doses",
    missedDoses = "Missed Doses",
    upcomingAppointments = "Upcoming Appointments",
    expiringSoon = "Medicines Expiring Soon",
    quickActions = "Quick Actions",
    addMedicine = "Add Medicine",
    addFamilyMember = "Add Family Member",
    addDoctor = "Add Doctor",
    addAppointment = "Add Appointment",
    uploadPrescription = "Upload Prescription",
    noMedicinesTitle = "You haven't added any medicines yet.",
    noFamilyMembersTitle = "Add your family members to manage their medicines.",
    noAppointmentsTitle = "No upcoming appointments.",
    noPrescriptionsTitle = "No prescriptions stored yet.",
    noDoctorsTitle = "No doctors added yet.",
    noCaregiversTitle = "No caregivers added yet.",
    noHistoryTitle = "No medication history recorded yet.",
    taken = "Taken",
    skip = "Skip",
    snooze = "Snooze",
    snooze10m = "10 minutes",
    snooze30m = "30 minutes",
    snooze1h = "1 hour",
    lowStock = "Medicine running low",
    expired = "Expired",
    expiringInDays = "Expiring in %d days",
    doctors = "Doctors",
    prescriptions = "Prescriptions",
    caregivers = "Caregivers",
    inventory = "Medicine Inventory",
    history = "Medication History",
    reports = "Reports & Export",
    settings = "Settings",
    search = "Search",
    notifications = "Notifications Center",
    aboutAuthor = "About Author",
    activeMedicines = "Active Medicines",
    profile = "Profile",
    edit = "Edit",
    delete = "Delete",
    save = "Save",
    cancel = "Cancel",
    confirmDelete = "Confirm Delete",
    confirmDeleteMsg = "Are you sure you want to delete this item? This action cannot be undone.",
    medicineName = "Medicine Name",
    genericName = "Generic Name",
    medicineType = "Medicine Type",
    strength = "Strength (e.g. 500)",
    unit = "Unit (mg, ml, drop, etc.)",
    dosage = "Dosage (e.g. 1 Tablet)",
    quantity = "Initial Quantity",
    remainingQuantity = "Remaining Quantity",
    minThreshold = "Low Stock Alert Threshold",
    startDate = "Start Date",
    endDate = "End Date",
    frequency = "Frequency",
    doseTimes = "Dose Times",
    addDoseTime = "+ Add Dose Time",
    beforeAfterFood = "Meal Timing",
    prescribedByDoctor = "Prescribed By Doctor",
    selectFamilyMember = "Family Member",
    medicineNotes = "Medicine Notes / Instructions",
    expiryDate = "Expiry Date",
    fullName = "Full Name",
    nickname = "Nickname",
    dob = "Date of Birth",
    gender = "Gender",
    bloodGroup = "Blood Group",
    phone = "Phone Number",
    relationship = "Relationship",
    doctorName = "Doctor Name",
    specialty = "Specialty",
    hospitalClinic = "Hospital / Clinic",
    email = "Email Address",
    address = "Address / Chamber",
    call = "Call",
    message = "Message",
    openMap = "Map",
    appointmentDate = "Appointment Date",
    appointmentTime = "Appointment Time",
    reason = "Reason for Visit",
    reminderTime = "Reminder Time",
    status = "Status",
    markCompleted = "Mark Completed",
    reschedule = "Reschedule",
    prescriptionTitle = "Prescription Title",
    notes = "Notes",
    caregiverName = "Caregiver Name",
    notifyMissed = "Notify on Missed Dose",
    notifyReminder = "Notify on Medicine Reminder",
    notifyAppointment = "Notify on Appointment",
    notifyExpiry = "Notify on Medicine Expiry",
    caregiverAlertInfo = "Caregivers can be contacted via phone or SMS when important medication events occur.",
    exportData = "Export Data (CSV / Text)",
    backupData = "Backup Data (JSON)",
    restoreData = "Restore Data",
    clearData = "Clear All Data",
    appPin = "App Lock PIN",
    privateNotification = "Private Notifications",
    privateNotificationDesc = "Hides medicine name in notifications for privacy ('You have a scheduled medicine')",
    language = "Language / ভাষা",
    appearance = "Appearance",
    lightMode = "Light Mode",
    darkMode = "Dark Mode",
    systemDefault = "System Default",
    getStarted = "Get Started",
    notificationPermissionDesc = "Medicine Sathi requires notification permission to remind you and your family when it is time to take doses and attend appointments.",
    allowNotifications = "Enable Notifications",
    complianceRate = "Adherence Rate",
    totalDoses = "Total Doses",
    searchPlaceholder = "Search medicines, doctors, family...",
    noResultsFound = "No matching results found.",
    all = "All"
)

val BengaliStrings = AppStrings(
    appName = "মেডিসিন সাথী",
    home = "হোম",
    medicines = "ওষুধসমূহ",
    calendar = "ক্যালেন্ডার",
    family = "পরিবার",
    more = "আরও",
    todayOverview = "আজকের সারসংক্ষেপ",
    todaysMedicines = "আজকের ওষুধসমূহ",
    upcomingDoses = "আসন্ন ডোজ",
    completedDoses = "গৃহীত ডোজ",
    missedDoses = "বাদ পড়া ডোজ",
    upcomingAppointments = "আসন্ন অ্যাপয়েন্টমেন্ট",
    expiringSoon = "মেয়াদ শীঘ্রই শেষ হচ্ছে",
    quickActions = "দ্রুত অ্যাকশন",
    addMedicine = "ওষুধ যোগ করুন",
    addFamilyMember = "পরিবারের সদস্য যোগ করুন",
    addDoctor = "ডাক্তার যোগ করুন",
    addAppointment = "অ্যাপয়েন্টমেন্ট যোগ করুন",
    uploadPrescription = "প্রেসক্রিপশন আপলোড",
    noMedicinesTitle = "আপনি এখনও কোনো ওষুধ যোগ করেননি।",
    noFamilyMembersTitle = "পরিবারের সদস্যদের ওষুধ পরিচালনার জন্য প্রোফাইল যোগ করুন।",
    noAppointmentsTitle = "কোনো আসন্ন অ্যাপয়েন্টমেন্ট নেই।",
    noPrescriptionsTitle = "কোনো প্রেসক্রিপশন সংরক্ষিত নেই।",
    noDoctorsTitle = "কোনো ডাক্তার যোগ করা হয়নি।",
    noCaregiversTitle = "কোনো কেয়ারগিভার যোগ করা হয়নি।",
    noHistoryTitle = "এখনও কোনো ওষুধ গ্রহণের ইতিহাস নেই।",
    taken = "খেয়েছি",
    skip = "বাদ দিন",
    snooze = "পরে মনে করান",
    snooze10m = "১০ মিনিট পর",
    snooze30m = "৩০ মিনিট পর",
    snooze1h = "১ ঘণ্টা পর",
    lowStock = "ওষুধের স্টক কম",
    expired = "মেয়াদ শেষ",
    expiringInDays = "%d দিনের মধ্যে মেয়াদ শেষ হবে",
    doctors = "ডাক্তারগণ",
    prescriptions = "প্রেসক্রিপশনসমূহ",
    caregivers = "কেয়ারগিভারগণ",
    inventory = "ওষুধ ইনভেন্টরি",
    history = "ওষুধের ইতিহাস",
    reports = "রিপোর্ট ও এক্সপোর্ট",
    settings = "সেটিংস",
    search = "অনুসন্ধান",
    notifications = "নোটিফিকেশন সেন্টার",
    aboutAuthor = "লেখক পরিচিতি",
    activeMedicines = "চলমান ওষুধসমূহ",
    profile = "প্রোফাইল",
    edit = "সম্পাদনা",
    delete = "মুছে ফেলুন",
    save = "সংরক্ষণ",
    cancel = "বাতিল",
    confirmDelete = "মুছে ফেলা নিশ্চিত করুন",
    confirmDeleteMsg = "আপনি কি নিশ্চিত যে এটি মুছে ফেলতে চান? এটি আর ফেরত আনা যাবে না।",
    medicineName = "ওষুধের নাম",
    genericName = "জেনেরিক নাম",
    medicineType = "ওষুধের ধরন",
    strength = "পাওয়ার (যেমন ৫০০)",
    unit = "একক (মিগ্রা, মিলি ইত্যাদি)",
    dosage = "ডোজের পরিমাণ (যেমন ১টি ট্যাবলেট)",
    quantity = "মোট পরিমাণ",
    remainingQuantity = "অবশিষ্ট পরিমাণ",
    minThreshold = "কম স্টকের সতর্কবার্তা সীমা",
    startDate = "শুরুর তারিখ",
    endDate = "শেষের তারিখ",
    frequency = "কত ঘন ঘন খাবেন",
    doseTimes = "ডোজের সময়",
    addDoseTime = "+ সময় যোগ করুন",
    beforeAfterFood = "খাওয়ার নিয়ম (আগে/পরে)",
    prescribedByDoctor = "প্রেসক্রিপশনকারী ডাক্তার",
    selectFamilyMember = "পরিবারের সদস্য",
    medicineNotes = "বিশেষ নির্দেশনা",
    expiryDate = "মেয়াদোত্তীর্ণ তারিখ",
    fullName = "পুরো নাম",
    nickname = "ডাকনাম",
    dob = "জন্ম তারিখ",
    gender = "লিঙ্গ",
    bloodGroup = "রক্তের গ্রুপ",
    phone = "ফোন নম্বর",
    relationship = "সম্পর্ক",
    doctorName = "ডাক্তারের নাম",
    specialty = "বিশেষজ্ঞতা",
    hospitalClinic = "হাসপাতাল / ক্লিনিক",
    email = "ইমেইল",
    address = "চেম্বারের ঠিকানা",
    call = "কল করুন",
    message = "মেসেজ",
    openMap = "ম্যাপ",
    appointmentDate = "অ্যাপয়েন্টমেন্টের তারিখ",
    appointmentTime = "সময়",
    reason = "সাক্ষাতের কারণ",
    reminderTime = "রিমাইন্ডারের সময়",
    status = "অবস্থা",
    markCompleted = "সম্পন্ন চিহ্নিত করুন",
    reschedule = "পুনর্নির্ধারণ",
    prescriptionTitle = "প্রেসক্রিপশনের শিরোনাম",
    notes = "নোট",
    caregiverName = "কেয়ারগিভারের নাম",
    notifyMissed = "ডোজ মিস হলে জানান",
    notifyReminder = "ওষুধের সময়ে জানান",
    notifyAppointment = "অ্যাপয়েন্টমেন্টের সময় জানান",
    notifyExpiry = "মেয়াদ শেষের সতর্কবার্তা",
    caregiverAlertInfo = "গুরুত্বপূর্ণ ওষুধ ইভেন্টে কেয়ারগিভারকে কল বা এসএমএসের মাধ্যমে অবগত করা যাবে।",
    exportData = "ডেটা এক্সপোর্ট (CSV / Text)",
    backupData = "ব্যাকআপ ডেটা (JSON)",
    restoreData = "রিস্টোর ডেটা",
    clearData = "সব ডেটা মুছে ফেলুন",
    appPin = "অ্যাপ লক পিন (PIN)",
    privateNotification = "গোপনীয় নোটিফিকেশন",
    privateNotificationDesc = "নোটিফিকেশনে ওষুধের নাম গোপন রাখে ('আপনার একটি নির্ধারিত ওষুধ রয়েছে')",
    language = "ভাষা / Language",
    appearance = "চেহারা (থিম)",
    lightMode = "লাইট মোড",
    darkMode = "ডার্ক মোড",
    systemDefault = "সিস্টেম ডিফল্ট",
    getStarted = "শুরু করুন",
    notificationPermissionDesc = "মেডিসিন সাথী সঠিক সময়ে আপনার ও পরিবারের সদস্যদের ওষুধের ডোজ ও অ্যাপয়েন্টমেন্ট মনে করিয়ে দিতে নোটিফিকেশন অনুমতি চায়।",
    allowNotifications = "নোটিফিকেশন চালু করুন",
    complianceRate = "নিয়মিত খাওয়ার হার",
    totalDoses = "মোট ডোজ",
    searchPlaceholder = "ওষুধ, ডাক্তার, পরিবার খুঁজুন...",
    noResultsFound = "কোনো তথ্য পাওয়া যায়নি।",
    all = "সব"
)

val LocalAppStrings = compositionLocalOf { EnglishStrings }

@Composable
fun appStrings(lang: String): AppStrings {
    return if (lang == "bn") BengaliStrings else EnglishStrings
}
